import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { fonts } from "./fonts";
import { Providers } from "./providers";
import { Container, HStack, VStack } from "@chakra-ui/react";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={fonts.rubik.variable}>
      <body className={inter.className}>
        <Providers>
          <Container maxW="container.xl">
            <HStack spacing="16px" as="nav">
              <Link href="/">Feed</Link>
              <Link href="/users">Users</Link>
            </HStack>
            <VStack spacing="24px" alignItems="flex-start">
              {children}
            </VStack>
          </Container>
        </Providers>
      </body>
    </html>
  );
}
